import { useState, type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { BookOpen, BrainCircuit, Plus, Search, Tag, X } from 'lucide-react';
import { getGetDashboardQueryKey, getListMemoryQueryKey, useCreateMemory, useListMemory } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { EmptyState, LoadingButton, PageIntro, Panel, QueryState } from '@/components/ui-blocks';

const categories = ['Context', 'Preference', 'Project', 'Decision'];
function relativeDate(value: string) { const date = new Date(value); if (Number.isNaN(date.getTime())) return 'Unknown'; const days = Math.round((Date.now() - date.getTime()) / 86400000); return days <= 0 ? 'Today' : days === 1 ? 'Yesterday' : `${days} days ago`; }

export default function Memory() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [category, setCategory] = useState(categories[0]);
  const [notice, setNotice] = useState('');
  const memory = useListMemory({ query: { queryKey: getListMemoryQueryKey() } });
  const create = useCreateMemory();
  const queryClient = useQueryClient();
  const submit = (event: FormEvent) => { event.preventDefault(); if (!title.trim() || !content.trim()) return; create.mutate({ data: { title: title.trim(), content: content.trim(), category } }, { onSuccess: () => { setTitle(''); setContent(''); setCategory(categories[0]); setOpen(false); setNotice('Memory saved to the shared context.'); queryClient.invalidateQueries({ queryKey: getListMemoryQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardQueryKey() }); }, onError: () => setNotice('Could not save this memory. Try again.') }); };
  const filtered = memory.data?.filter((entry) => `${entry.title} ${entry.content} ${entry.category}`.toLowerCase().includes(query.toLowerCase())) ?? [];

  return <AppShell><PageIntro eyebrow="Shared context" title="Agent memory" description="A small, durable layer of context shared between VS Code and Kali Linux." action={<button onClick={() => { setOpen(true); setNotice(''); }} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-extrabold text-primary-foreground transition-transform hover:brightness-105 active:scale-[0.98]" data-testid="button-new-memory"><Plus size={15} /> New memory</button>} />
    {notice && <div className={`mb-4 rounded-xl border px-4 py-3 text-xs font-bold ${notice.includes('Could') ? 'border-destructive/25 bg-destructive/5 text-destructive' : 'border-primary/20 bg-primary/5 text-primary'}`} data-testid="status-memory-action">{notice}</div>}
    {open && <div className="mb-4 rounded-2xl border border-primary/25 bg-card shadow-[0_8px_28px_hsl(211_38%_15%/0.05)]"><div className="flex items-center justify-between border-b border-border/70 px-5 py-4"><div><h2 className="text-sm font-extrabold">Save shared memory</h2><p className="mt-0.5 text-[11px] text-muted-foreground">This will be available to both connected environments.</p></div><button onClick={() => setOpen(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Close memory form" data-testid="button-close-memory-form"><X size={17} /></button></div><form onSubmit={submit} className="grid gap-4 p-5 md:grid-cols-[1fr_180px]"><div className="space-y-4"><div><label htmlFor="memory-title" className="text-xs font-extrabold">Title</label><input id="memory-title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="For example: deploy checklist" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" data-testid="input-memory-title" /></div><div><label htmlFor="memory-content" className="text-xs font-extrabold">What should the agent remember?</label><textarea id="memory-content" value={content} onChange={(event) => setContent(event.target.value)} placeholder="Keep the staging branch protected until QA signs off." rows={4} className="mt-2 w-full resize-none rounded-xl border border-input bg-background px-3 py-3 text-xs leading-5 outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" data-testid="input-memory-content" /></div></div><div className="flex flex-col"><label htmlFor="memory-category" className="text-xs font-extrabold">Category</label><select id="memory-category" value={category} onChange={(event) => setCategory(event.target.value)} className="mt-2 h-11 rounded-xl border border-input bg-background px-3 text-xs outline-none focus:border-primary" data-testid="select-memory-category">{categories.map((item) => <option key={item}>{item}</option>)}</select><LoadingButton type="submit" pending={create.isPending} className="mt-auto w-full" data-testid="button-save-memory">Save memory</LoadingButton></div></form></div>}
    <Panel title="Memory shelf" kicker={memory.data ? `${memory.data.length} entries · shared across environments` : 'Shared across environments'} action={<div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter memory" className="h-8 w-[150px] rounded-lg border border-input bg-background pl-8 pr-2 text-[11px] outline-none focus:border-primary" aria-label="Filter memory" data-testid="input-filter-memory" /></div>}>
      <QueryState loading={memory.isLoading} error={memory.isError} retry={() => memory.refetch()} label="memory">{filtered.length ? <div className="grid gap-3 p-4 md:grid-cols-2">{filtered.map((entry) => <article key={entry.id} className="group rounded-xl border border-border/80 bg-background p-4 transition-colors hover:border-primary/35" data-testid={`card-memory-${entry.id}`}><div className="flex items-start justify-between gap-3"><span className="flex items-center gap-1.5 rounded-full bg-secondary px-2 py-1 text-[10px] font-extrabold uppercase tracking-wider text-primary"><Tag size={11} />{entry.category}</span><span className="text-[10px] text-muted-foreground">{relativeDate(entry.updatedAt)}</span></div><h3 className="mt-4 text-sm font-extrabold">{entry.title}</h3><p className="mt-2 line-clamp-3 text-xs leading-5 text-muted-foreground">{entry.content}</p><div className="mt-4 flex items-center gap-1.5 text-[10px] font-bold text-muted-foreground"><BrainCircuit size={12} className="text-primary" /> Remembered by Northstar</div></article>)}</div> : <EmptyState icon={<BookOpen size={22} />} title={query ? 'No matching memories' : 'Your shared context is clear'} description={query ? 'Try a different phrase or category.' : 'Capture decisions, preferences, and project context once. The agent can use them everywhere.'} action={!query ? <button onClick={() => setOpen(true)} className="rounded-xl bg-primary px-4 py-2.5 text-xs font-extrabold text-primary-foreground" data-testid="button-empty-new-memory">Save first memory</button> : undefined} />}</QueryState>
    </Panel>
  </AppShell>;
}